### ISSUE TITLE
Suggestion: Remembering Custom Items Via Cookies

### ISSUE THREAD

**Issue by alexis-evelyn** [destruc7i0n/crafting#19]
I'd like to use cookies to remember my custom items I add to the interface. I'm working on a mod and use this site to aid in my creating crafting recipes. Thanks!

**Comment by McJoe21** [comment]
That would be cool

**Comment by destruc7i0n** [comment]
Apologies for how long this took! I had apparently stopped watching this and didn't receive any notifications whatsoever.

This should be added now :)
