### ISSUE TITLE
Edit Custom Data doesnt change anything

### ISSUE THREAD

**Issue by xhendrikg** [destruc7i0n/crafting#21]
Is that a bug?

**Comment by destruc7i0n** [comment]
Custom data is mostly meant for adding additional tags to the items. It wouldn't change anything in java.
Unless you mean that the tags are not showing up in the output? If so, then can you show me a screenshot of it like that?

**Comment by xhendrikg** [comment]
> 
> 
> Custom data is mostly meant for adding additional tags to the items. It wouldn't change anything in java.
> Unless you mean that the tags are not showing up in the output? If so, then can you show me a screenshot of it like that?

is that feature only for bedrock?

**Comment by destruc7i0n** [comment]
Yeah, currently the custom item data is most useful for bedrock and maybe those playing modded.
