### ISSUE TITLE
Suggestion: Add Support For Soul Campfire and Smithing Table Recipes

### ISSUE THREAD

**Issue by Chikorita-Lover** [destruc7i0n/crafting#24]
Support for soul campfire and smithing table recipes have recently been added for Bedrock Edition. I don't remember if soul campfire recipes are in a stable release, but smithing table recipes are.

**Comment by destruc7i0n** [comment]
There is support for campfire and soul campfire 
<img width="558" alt="image" src="https://user-images.githubusercontent.com/6181960/174195552-2750b164-22df-4fef-a65d-b5537a8bb813.png">

I'll add smithing table as well.
