### ISSUE TITLE
Support for 1.20.5+

### ISSUE THREAD

**Issue by vico93** [destruc7i0n/crafting#32]
[Starting with 1.20.5](https://minecraft.wiki/w/Data_component_format), Minecraft (Java) did some changes in the internal data of items and blocks and this resulted in changes in the `result` field, now the former `item` property was renamed to `id` and inline `result` (only with the item id straight on it) was discontinued, the `result` always is a key with `id`, `count` and `components` (formerly the nbt stuff, if applicable). The link on the start of the paragraph details how its done now.

**Comment by MISTERPUG51** [comment]
I just came here to report this, I spent 30 minutes trying to figure out why my recipe wont work.

**Comment by destruc7i0n** [comment]
This has been updated with the release of 1.21 on the site.

**Comment by vico93** [comment]
@destruc7i0n a detail: on the smelting tab, the output is still spitting the item id directly under `result`:
![image](https://github.com/destruc7i0n/crafting/assets/3485505/02b79f4a-9bd1-45b1-8d01-f2b8c76a862c)
...when vanilla smelting files also spits the `result` as an object with `id`:
![image](https://github.com/destruc7i0n/crafting/assets/3485505/1d6cafa7-34d3-4f2f-82d1-f3b4cf26cffb)

I think others like blasting, smoking, campfire and stonecutter are also in this format.

**Comment by destruc7i0n** [comment]
@vico93 thanks for calling out! I had fixed this but forgot to deploy, should be up now.
