### ISSUE TITLE
Recipe for Spawn Eggs Impossible

### ISSUE THREAD

**Issue by andybond006** [destruc7i0n/crafting#4]
### Description
Due to Spawn Eggs requiring an [EntityTag](http://minecraft.gamepedia.com/Spawn_Egg#Data_values) to specify the type of mob to spawn, it appears to be currently impossible to create a crafting recipe for any spawn egg other than an "empty" spawn egg.
### Demonstration of Issue
Here is an example recipe that, when used in game, will yield a generic spawn egg and **not** a Zombie Spawn Egg as intended.
``` json
{
    "type": "crafting_shaped",
    "pattern": [
        "###",
        "#E#",
        "###"
    ],
    "key": {
        "#": {
            "item": "minecraft:skull",
            "data": 2
        },
        "E": {
            "item": "minecraft:egg"
        }
    },
    "result": {
        "item": "minecraft:spawn_egg",
        "data": 54,
        "count": 1
    }
}
```
### Possible Solutions

- Wait for 1.13 to see if there is a way to add NBT data to recipe inputs and outputs
- Remove spawn eggs from the recipe generator temporarily (or disable them?)

**Comment by destruc7i0n** [comment]
GitHub seems to have not notified me about this earlier - sorry for the long delay...

For now I think I'll just temporarily disable them, I'll commit this tomorrow and see what 1.13 brings for this!

Thanks :)

**Comment by andybond006** [comment]
I think this particular issue was resolved by Mojang removing metadata.

Thanks for making a great tool!
