### ISSUE TITLE
Display the count next to the output ingredient

### ISSUE THREAD

**Issue by Asha20** [destruc7i0n/crafting#8]
Right now, there isn't an obvious way to find out the output ingredient's count except by looking at the resulting JSON. It would be nice if you could see a number displayed next to the image, just like in Minecraft.

I'm still very new to contributing to open source projects, so I'm eager to make a PR for this issue if that's okay!

**Comment by destruc7i0n** [comment]
This has been added as of the latest version! Terribly sorry for taking so long to do this :)
